apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-maracartman-com-tls
  namespace: cert-manager-namespace
spec:
  secretName: k8s-maracartman-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-maracartman.com
  dnsNames:
    - k8s-maracartman.com
    - www.k8s-maracartman.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-maracartman.com
          - www.k8s-maracartman.com